/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import Data.*;
import dbConnection.Connector;
import java.sql.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author ASUS
 */
public class dashboard extends javax.swing.JFrame {
    private Users user;
    private int currentBack = 0;

    /**
     * Creates new form login
     */
    public dashboard() {
        initComponents();
        tanggal.setBackground(new java.awt.Color(10,10,10,20));
        totalP_box.setBackground(new java.awt.Color(10,10,10,20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void setupBarChart() {
        LocalDate today = LocalDate.now();
        LocalDate targetDate = today.minusMonths(currentBack);

        int month = targetDate.getMonthValue();
        int year = targetDate.getYear();
        totalPengeluaranLabel.setText(String.valueOf(user.getDataPengeluaranPerBulan(month, year)));

        BarChart barChart = new BarChart(user, month, year);
        GrafikBar.removeAll(); 
        GrafikBar.setLayout(new BorderLayout());   
        GrafikBar.add(barChart, BorderLayout.CENTER);
        GrafikBar.revalidate(); 
        GrafikBar.repaint(); 
        
        updateDate(targetDate);
    }
    
    private void updateDate(LocalDate date){
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("MMMM yyyy");
        
        tahun.setText(date.format(formatter));
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanel = new javax.swing.JScrollPane();
        parent = new javax.swing.JPanel();
        profil_button = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        totalPengeluaranLabel = new javax.swing.JLabel();
        total_pengeluaran_text = new javax.swing.JLabel();
        kanan_button = new javax.swing.JButton();
        right_button = new javax.swing.JButton();
        tahun = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        totalP_box = new javax.swing.JLabel();
        inputButton = new javax.swing.JButton();
        bg = new javax.swing.JLabel();
        GrafikBar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        scrollPanel.setBackground(new java.awt.Color(204, 102, 0));
        scrollPanel.setBorder(null);
        scrollPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPanel.setToolTipText("");
        scrollPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrollPanel.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        scrollPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        scrollPanel.setOpaque(false);

        parent.setMaximumSize(new java.awt.Dimension(320, 800));
        parent.setOpaque(false);
        parent.setPreferredSize(new java.awt.Dimension(320, 800));
        parent.setLayout(null);

        profil_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.png"))); // NOI18N
        profil_button.setBorderPainted(false);
        profil_button.setContentAreaFilled(false);
        profil_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profil_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profil_buttonActionPerformed(evt);
            }
        });
        parent.add(profil_button);
        profil_button.setBounds(10, 10, 40, 60);

        logo.setFont(new java.awt.Font("Colonna MT", 2, 24)); // NOI18N
        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setText("Easy CF");
        parent.add(logo);
        logo.setBounds(220, 10, 100, 60);

        usernameLabel.setFont(new java.awt.Font("Onest Bold", 0, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setText("username label");
        parent.add(usernameLabel);
        usernameLabel.setBounds(60, 20, 160, 40);

        totalPengeluaranLabel.setFont(new java.awt.Font("Onest Bold", 0, 12)); // NOI18N
        totalPengeluaranLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalPengeluaranLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        totalPengeluaranLabel.setText("XXXXXXXXXXX");
        parent.add(totalPengeluaranLabel);
        totalPengeluaranLabel.setBounds(190, 220, 140, 30);

        total_pengeluaran_text.setFont(new java.awt.Font("Onest Bold", 0, 12)); // NOI18N
        total_pengeluaran_text.setForeground(new java.awt.Color(255, 255, 255));
        total_pengeluaran_text.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        total_pengeluaran_text.setText("Total pengeluaran:  Rp.");
        parent.add(total_pengeluaran_text);
        total_pengeluaran_text.setBounds(50, 210, 140, 50);

        kanan_button.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        kanan_button.setForeground(new java.awt.Color(255, 255, 255));
        kanan_button.setText("<");
        kanan_button.setContentAreaFilled(false);
        kanan_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kanan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kanan_buttonActionPerformed(evt);
            }
        });
        parent.add(kanan_button);
        kanan_button.setBounds(30, 140, 50, 48);

        right_button.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        right_button.setForeground(new java.awt.Color(255, 255, 255));
        right_button.setText(">");
        right_button.setContentAreaFilled(false);
        right_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        right_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                right_buttonActionPerformed(evt);
            }
        });
        parent.add(right_button);
        right_button.setBounds(240, 140, 50, 48);

        tahun.setFont(new java.awt.Font("Onest Bold", 0, 16)); // NOI18N
        tahun.setForeground(new java.awt.Color(255, 255, 255));
        tahun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tahun.setText("Bulan_Tahun");
        parent.add(tahun);
        tahun.setBounds(70, 140, 180, 50);

        tanggal.setBackground(new java.awt.Color(51, 102, 0));
        tanggal.setForeground(new java.awt.Color(255, 255, 255));
        tanggal.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), null));
        tanggal.setOpaque(true);
        parent.add(tanggal);
        tanggal.setBounds(30, 140, 260, 50);

        totalP_box.setBackground(new java.awt.Color(51, 102, 0));
        totalP_box.setForeground(new java.awt.Color(255, 255, 255));
        totalP_box.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), null));
        totalP_box.setOpaque(true);
        parent.add(totalP_box);
        totalP_box.setBounds(30, 210, 260, 50);

        inputButton.setBackground(new java.awt.Color(0, 50, 0));
        inputButton.setFont(new java.awt.Font("Onest Bold", 0, 12)); // NOI18N
        inputButton.setForeground(new java.awt.Color(255, 255, 255));
        inputButton.setText("⊕Catat Pengeluaran");
        inputButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        inputButton.setBorderPainted(false);
        inputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputButtonActionPerformed(evt);
            }
        });
        parent.add(inputButton);
        inputButton.setBounds(30, 90, 260, 30);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setForeground(new java.awt.Color(255, 255, 255));
        bg.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main page.png"))); // NOI18N
        bg.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bg.setAlignmentX(0.5F);
        bg.setAutoscrolls(true);
        bg.setName(""); // NOI18N
        bg.setRequestFocusEnabled(false);
        parent.add(bg);
        bg.setBounds(0, 0, 320, 800);
        parent.add(GrafikBar);
        GrafikBar.setBounds(30, 280, 260, 220);

        scrollPanel.setViewportView(parent);

        getContentPane().add(scrollPanel);

        setBounds(560, 160, 332, 806);
    }// </editor-fold>//GEN-END:initComponents

    public void setUser(Users user){
        this.user = user;
        setupBarChart();
        if (user instanceof Biodata) {
            Biodata biodata = (Biodata) user;
             
            String nama = biodata.getNama();
            usernameLabel.setText(nama);
        }
    }
    
    public Users getUser(){
        return this.user;
    }
    
    private void profil_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profil_buttonActionPerformed
        profile profilePage = new profile();
        profilePage.setUser(this.user);
        profilePage.setVisible(true);
        profilePage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_profil_buttonActionPerformed

    private void kanan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kanan_buttonActionPerformed
        if(currentBack < 12){
            currentBack++;
            setupBarChart();
        }
    }//GEN-LAST:event_kanan_buttonActionPerformed

    private void right_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_right_buttonActionPerformed
        if(currentBack > 0){
            currentBack--;
            setupBarChart();
        }
    }//GEN-LAST:event_right_buttonActionPerformed

    private void inputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputButtonActionPerformed
        input inputPage = new input();
        inputPage.setUser(this.user);
        inputPage.setVisible(true);
        inputPage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_inputButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dashboard db = new dashboard();
                db.setVisible(true);
                db.setSize(330, 545);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GrafikBar;
    private javax.swing.JLabel bg;
    private javax.swing.JButton inputButton;
    private javax.swing.JButton kanan_button;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel parent;
    private javax.swing.JButton profil_button;
    private javax.swing.JButton right_button;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JLabel tahun;
    private javax.swing.JLabel tanggal;
    private javax.swing.JLabel totalP_box;
    private javax.swing.JLabel totalPengeluaranLabel;
    private javax.swing.JLabel total_pengeluaran_text;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
