/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import Data.Pengeluaran;
import Data.Users;
import dbConnection.Connector;

import java.awt.Color;
import java.awt.Font;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class input extends javax.swing.JFrame {

    private Users user;
    /**
     * Creates new form login
     */
    public input() {
        initComponents();
        judul_field.setBackground(new java.awt.Color(0,0,0,1));
        jumlah_field.setBackground(new java.awt.Color(0,0,0,1));
        deskripsi_field.setBackground(new java.awt.Color(0,0,0,1));
        judul_field.setText("  Masukkan judul");
        judul_field.setFont(new Font("Segoe UI", Font.ITALIC, 13));
        judul_field.setForeground(new Color(153, 153, 153));
        jumlah_field.setText("  Masukkan total pengeluaran");
        jumlah_field.setFont(new Font("Segoe UI", Font.ITALIC, 13));
        jumlah_field.setForeground(new Color(153, 153, 153));
        deskripsi_field.setText("  Masukkan deskripsi");
        deskripsi_field.setFont(new Font("Segoe UI", Font.ITALIC, 13));
        deskripsi_field.setForeground(new Color(153, 153, 153));
        
    }

    public void setUser(Users user){
        this.user = user;
    }
    
    public Users getUser(){
        return this.user;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kategoriGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        frame_atas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        frame_field = new javax.swing.JPanel();
        judul_text = new javax.swing.JLabel();
        frame_bawah = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        password_text = new javax.swing.JLabel();
        jumlah_field = new javax.swing.JTextField();
        submit_button = new javax.swing.JButton();
        cancle_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        judul_field = new javax.swing.JTextField();
        deskripsi_field = new javax.swing.JTextField();
        deskripsi_text = new javax.swing.JLabel();
        kategori_text = new javax.swing.JLabel();
        makananCB = new javax.swing.JCheckBox();
        belanjaCB = new javax.swing.JCheckBox();
        lainnyaCB = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        frame_atas.setBackground(new java.awt.Color(0, 0, 0));
        frame_atas.setForeground(new java.awt.Color(255, 255, 255));
        frame_atas.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Onest Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Catat Pengeluaranmu!");

        jLabel2.setFont(new java.awt.Font("Onest Light", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout frame_atasLayout = new javax.swing.GroupLayout(frame_atas);
        frame_atas.setLayout(frame_atasLayout);
        frame_atasLayout.setHorizontalGroup(
            frame_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_atasLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_atasLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28))
        );
        frame_atasLayout.setVerticalGroup(
            frame_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_atasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        jPanel1.add(frame_atas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 320, 40));

        frame_field.setBackground(new java.awt.Color(0, 0, 0));
        frame_field.setForeground(new java.awt.Color(255, 255, 255));
        frame_field.setOpaque(false);

        judul_text.setBackground(new java.awt.Color(255, 255, 255));
        judul_text.setFont(new java.awt.Font("Onest Bold", 0, 12)); // NOI18N
        judul_text.setForeground(new java.awt.Color(255, 255, 255));
        judul_text.setText("Judul:");

        frame_bawah.setBackground(new java.awt.Color(0, 0, 0));
        frame_bawah.setToolTipText("");
        frame_bawah.setOpaque(false);

        jLabel7.setText(" ");

        password_text.setFont(new java.awt.Font("Onest Bold", 0, 12)); // NOI18N
        password_text.setForeground(new java.awt.Color(255, 255, 255));
        password_text.setText("Jumlah Pengeluaran:");

        jumlah_field.setFont(new java.awt.Font("Onest Regular", 0, 14)); // NOI18N
        jumlah_field.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), null));
        jumlah_field.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jumlah_field.setMargin(new java.awt.Insets(1, 10, 1, 1));
        jumlah_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jumlah_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jumlah_fieldFocusLost(evt);
            }
        });
        jumlah_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah_fieldActionPerformed(evt);
            }
        });

        submit_button.setBackground(new java.awt.Color(30, 50, 0));
        submit_button.setFont(new java.awt.Font("Onest Light", 0, 12)); // NOI18N
        submit_button.setForeground(new java.awt.Color(255, 255, 255));
        submit_button.setText("Submit");
        submit_button.setBorder(null);
        submit_button.setBorderPainted(false);
        submit_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_buttonActionPerformed(evt);
            }
        });

        cancle_button.setBackground(new java.awt.Color(0, 0, 114));
        cancle_button.setFont(new java.awt.Font("Onest Light", 0, 12)); // NOI18N
        cancle_button.setForeground(new java.awt.Color(255, 255, 255));
        cancle_button.setText("Cancle");
        cancle_button.setBorder(null);
        cancle_button.setBorderPainted(false);
        cancle_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancle_buttonActionPerformed(evt);
            }
        });

        delete_button.setBackground(new java.awt.Color(115, 0, 0));
        delete_button.setFont(new java.awt.Font("Onest Light", 0, 12)); // NOI18N
        delete_button.setForeground(new java.awt.Color(255, 255, 255));
        delete_button.setText("Delete");
        delete_button.setBorder(null);
        delete_button.setBorderPainted(false);
        delete_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frame_bawahLayout = new javax.swing.GroupLayout(frame_bawah);
        frame_bawah.setLayout(frame_bawahLayout);
        frame_bawahLayout.setHorizontalGroup(
            frame_bawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_bawahLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(frame_bawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(frame_bawahLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(frame_bawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(frame_bawahLayout.createSequentialGroup()
                            .addComponent(cancle_button, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(submit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_bawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumlah_field, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password_text, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(48, 48, 48))
        );
        frame_bawahLayout.setVerticalGroup(
            frame_bawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_bawahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(password_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jumlah_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(frame_bawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancle_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        judul_field.setFont(new java.awt.Font("Onest Regular", 0, 14)); // NOI18N
        judul_field.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), null));
        judul_field.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        judul_field.setMargin(new java.awt.Insets(1, 10, 1, 1));
        judul_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                judul_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                judul_fieldFocusLost(evt);
            }
        });
        judul_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judul_fieldActionPerformed(evt);
            }
        });

        deskripsi_field.setFont(new java.awt.Font("Onest Regular", 0, 14)); // NOI18N
        deskripsi_field.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), null));
        deskripsi_field.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        deskripsi_field.setMargin(new java.awt.Insets(1, 10, 1, 1));
        deskripsi_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                deskripsi_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                deskripsi_fieldFocusLost(evt);
            }
        });
        deskripsi_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskripsi_fieldActionPerformed(evt);
            }
        });

        deskripsi_text.setBackground(new java.awt.Color(255, 255, 255));
        deskripsi_text.setFont(new java.awt.Font("Onest Bold", 0, 12)); // NOI18N
        deskripsi_text.setForeground(new java.awt.Color(255, 255, 255));
        deskripsi_text.setText("Deskripsi:");

        kategori_text.setBackground(new java.awt.Color(255, 255, 255));
        kategori_text.setFont(new java.awt.Font("Onest Bold", 0, 12)); // NOI18N
        kategori_text.setForeground(new java.awt.Color(255, 255, 255));
        kategori_text.setText("Kategori:");

        kategoriGroup.add(makananCB);
        makananCB.setForeground(new java.awt.Color(255, 255, 255));
        makananCB.setText("Makanan & Minuman");
        makananCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makananCBActionPerformed(evt);
            }
        });

        kategoriGroup.add(belanjaCB);
        belanjaCB.setForeground(new java.awt.Color(255, 255, 255));
        belanjaCB.setText("Belanja");
        belanjaCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                belanjaCBActionPerformed(evt);
            }
        });

        kategoriGroup.add(lainnyaCB);
        lainnyaCB.setForeground(new java.awt.Color(255, 255, 255));
        lainnyaCB.setText("Lainnya");
        lainnyaCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lainnyaCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frame_fieldLayout = new javax.swing.GroupLayout(frame_field);
        frame_field.setLayout(frame_fieldLayout);
        frame_fieldLayout.setHorizontalGroup(
            frame_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_fieldLayout.createSequentialGroup()
                .addGroup(frame_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frame_fieldLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(frame_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(judul_text, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(judul_field, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deskripsi_text, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deskripsi_field, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kategori_text, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(makananCB, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(belanjaCB, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lainnyaCB, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(frame_fieldLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(frame_bawah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frame_fieldLayout.setVerticalGroup(
            frame_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_fieldLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(judul_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(judul_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deskripsi_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deskripsi_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kategori_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(makananCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(belanjaCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lainnyaCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(frame_bawah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jPanel1.add(frame_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 320, 470));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BG.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_buttonActionPerformed
        String judul = judul_field.getText();
        String deskripsi = deskripsi_field.getText();
        String kategori = "";
        
        if (makananCB.isSelected()){
            kategori = "Makanan & Minuman";
        } 
        else if (belanjaCB.isSelected()){
            kategori = "Belanja";
        }
        else{
            kategori = "Lainnya";
        }
        
        int jumlahPengeluaran = Integer.parseInt(jumlah_field.getText());

        LocalDate tanggal = LocalDate.now();
        String tgl = tanggal.toString(); 
        
        Pengeluaran pengeluaran = new Pengeluaran(judul, deskripsi, kategori, jumlahPengeluaran, tgl);
        
        String query = "INSERT INTO pengeluaran (judul, deskripsi, tipe_pengeluaran, uang_keluar, tanggal, username) " +
               "VALUES ('" + judul + "', '" + deskripsi + "', '" + kategori + "', " + jumlahPengeluaran + ", '" + tgl + "', '" + this.user.getUsername() + "')";

        Connector conn = new Connector();
        if (conn.executeUpdate(query)){
            JOptionPane.showMessageDialog(null, "Data berhasil dimasukkan!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Gagal memasukkan data! "+JOptionPane.ERROR_MESSAGE, "Error", JOptionPane.ERROR_MESSAGE);

        }

        dashboard db = new dashboard();
        db.setUser(this.user);
        db.setVisible(true);
        db.setSize(330, 545);
        
        this.dispose();
        
    }//GEN-LAST:event_submit_buttonActionPerformed

    private void jumlah_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah_fieldActionPerformed
        
    }//GEN-LAST:event_jumlah_fieldActionPerformed

    private void jumlah_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jumlah_fieldFocusGained
        if (jumlah_field.getText().equals("  Masukkan total pengeluaran")){
            jumlah_field.setText("");
            jumlah_field.setForeground(new Color(255, 255, 255));
            jumlah_field.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        }
    }//GEN-LAST:event_jumlah_fieldFocusGained

    private void jumlah_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jumlah_fieldFocusLost
        if (jumlah_field.getText().equals("")){
            jumlah_field.setText("  Masukkan total pengeluaran");
            jumlah_field.setForeground(new Color(153, 153, 153));
            jumlah_field.setFont(new Font("Segoe UI", Font.ITALIC, 13));
        }
    }//GEN-LAST:event_jumlah_fieldFocusLost

    private void makananCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makananCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_makananCBActionPerformed

    private void belanjaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_belanjaCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_belanjaCBActionPerformed

    private void lainnyaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lainnyaCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lainnyaCBActionPerformed

    private void deskripsi_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskripsi_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deskripsi_fieldActionPerformed

    private void deskripsi_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deskripsi_fieldFocusLost
        if (deskripsi_field.getText().equals("")){
            deskripsi_field.setText("  Masukkan deskripsi");
            deskripsi_field.setForeground(new Color(153, 153, 153));
            deskripsi_field.setFont(new Font("Segoe UI", Font.ITALIC, 13));
        }
    }//GEN-LAST:event_deskripsi_fieldFocusLost

    private void deskripsi_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deskripsi_fieldFocusGained
        if (deskripsi_field.getText().equals("  Masukkan deskripsi")){
            deskripsi_field.setText("");
            deskripsi_field.setForeground(new Color(255, 255, 255));
            deskripsi_field.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        }
    }//GEN-LAST:event_deskripsi_fieldFocusGained

    private void judul_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judul_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_judul_fieldActionPerformed

    private void judul_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_judul_fieldFocusLost
        if (judul_field.getText().equals("")){
            judul_field.setText("  Masukkan judul");
            judul_field.setForeground(new Color(153, 153, 153));
            judul_field.setFont(new Font("Segoe UI", Font.ITALIC, 13));
        }
    }//GEN-LAST:event_judul_fieldFocusLost

    private void judul_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_judul_fieldFocusGained
        if (judul_field.getText().equals("  Masukkan judul")){
            judul_field.setText("");
            judul_field.setForeground(new Color(255, 255, 255));
            judul_field.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        }
    }//GEN-LAST:event_judul_fieldFocusGained

    private void cancle_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancle_buttonActionPerformed
        dashboard db = new dashboard();
        db.setUser(this.user);
        db.setVisible(true);
        db.setSize(330, 545);
        this.dispose();
    }//GEN-LAST:event_cancle_buttonActionPerformed

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        judul_field.setText("");
        judul_field.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        jumlah_field.setText("  Masukkan total pengeluaran");
        jumlah_field.setForeground(new Color(153, 153, 153));
        jumlah_field.setFont(new Font("Segoe UI", Font.ITALIC, 13));
        deskripsi_field.setText("  Masukkan deskripsi");
        deskripsi_field.setForeground(new Color(153, 153, 153));
        deskripsi_field.setFont(new Font("Segoe UI", Font.ITALIC, 13));
        kategoriGroup.clearSelection();
        judul_field.requestFocus();
    }//GEN-LAST:event_delete_buttonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                input login = new input();
                login.setVisible(true);
                login.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox belanjaCB;
    private javax.swing.JButton cancle_button;
    private javax.swing.JButton delete_button;
    private javax.swing.JTextField deskripsi_field;
    private javax.swing.JLabel deskripsi_text;
    private javax.swing.JPanel frame_atas;
    private javax.swing.JPanel frame_bawah;
    private javax.swing.JPanel frame_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField judul_field;
    private javax.swing.JLabel judul_text;
    private javax.swing.JTextField jumlah_field;
    private javax.swing.ButtonGroup kategoriGroup;
    private javax.swing.JLabel kategori_text;
    private javax.swing.JCheckBox lainnyaCB;
    private javax.swing.JCheckBox makananCB;
    private javax.swing.JLabel password_text;
    private javax.swing.JButton submit_button;
    // End of variables declaration//GEN-END:variables

    private String StringValueof(LocalDate tanggal) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
