/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import dbConnection.*;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author ASUS
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        username_field.setForeground(java.awt.Color.WHITE);
        username_field.setBackground(new java.awt.Color(0,0,0,1));
        password_field.setForeground(java.awt.Color.WHITE);
        password_field.setBackground(new java.awt.Color(0,0,0,1));username_field.setText("  Enter Username");
        username_field.setFont(new Font("Segoe UI", Font.ITALIC, 13));
        username_field.setForeground(new Color(153, 153, 153));
        password_field.setText("  Enter Password");
        password_field.setFont(new Font("Segoe UI", Font.ITALIC, 13));
        password_field.setForeground(new Color(153, 153, 153));
        password_field.setEchoChar((char) 0);
    }
    
    public void setUsername(String username){
        username_field.setText(username);
        username_field.setForeground(new Color(255, 255, 255));
        username_field.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        password_field.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        frame_atas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        frame_field = new javax.swing.JPanel();
        username_field = new javax.swing.JTextField();
        login_button = new javax.swing.JButton();
        password_field = new javax.swing.JPasswordField();
        username_text = new javax.swing.JLabel();
        password_text = new javax.swing.JLabel();
        frame_bawah = new javax.swing.JPanel();
        toRegister_text = new javax.swing.JLabel();
        toRegister_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        frame_atas.setBackground(new java.awt.Color(0, 0, 0));
        frame_atas.setForeground(new java.awt.Color(255, 255, 255));
        frame_atas.setAutoscrolls(true);
        frame_atas.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Onest Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome Back !");

        jLabel2.setFont(new java.awt.Font("Onest Light", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sign in to continue");

        javax.swing.GroupLayout frame_atasLayout = new javax.swing.GroupLayout(frame_atas);
        frame_atas.setLayout(frame_atasLayout);
        frame_atasLayout.setHorizontalGroup(
            frame_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_atasLayout.createSequentialGroup()
                .addGroup(frame_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frame_atasLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1))
                    .addGroup(frame_atasLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel2)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        frame_atasLayout.setVerticalGroup(
            frame_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_atasLayout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jPanel1.add(frame_atas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 320, 170));

        frame_field.setBackground(new java.awt.Color(0, 0, 0));
        frame_field.setForeground(new java.awt.Color(255, 255, 255));
        frame_field.setAutoscrolls(true);
        frame_field.setOpaque(false);

        username_field.setFont(new java.awt.Font("Onest Regular", 0, 14)); // NOI18N
        username_field.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), null));
        username_field.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        username_field.setMargin(new java.awt.Insets(1, 10, 1, 1));
        username_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                username_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                username_fieldFocusLost(evt);
            }
        });
        username_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_fieldActionPerformed(evt);
            }
        });
        username_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                username_fieldKeyPressed(evt);
            }
        });

        login_button.setBackground(new java.awt.Color(30, 50, 0));
        login_button.setFont(new java.awt.Font("Onest Light", 0, 12)); // NOI18N
        login_button.setForeground(new java.awt.Color(255, 255, 255));
        login_button.setText("Login");
        login_button.setBorder(null);
        login_button.setBorderPainted(false);
        login_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });

        password_field.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        password_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                password_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                password_fieldFocusLost(evt);
            }
        });
        password_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_fieldActionPerformed(evt);
            }
        });

        username_text.setBackground(new java.awt.Color(255, 255, 255));
        username_text.setFont(new java.awt.Font("Onest Light", 0, 12)); // NOI18N
        username_text.setForeground(new java.awt.Color(255, 255, 255));
        username_text.setText("Username: ");

        password_text.setFont(new java.awt.Font("Onest Light", 0, 12)); // NOI18N
        password_text.setForeground(new java.awt.Color(255, 255, 255));
        password_text.setText("Password:");

        javax.swing.GroupLayout frame_fieldLayout = new javax.swing.GroupLayout(frame_field);
        frame_field.setLayout(frame_fieldLayout);
        frame_fieldLayout.setHorizontalGroup(
            frame_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_fieldLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(frame_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username_text, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_text, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(frame_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(login_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(frame_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(username_field, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(password_field))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        frame_fieldLayout.setVerticalGroup(
            frame_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_fieldLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(username_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(password_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(frame_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 166, 320, 210));

        frame_bawah.setBackground(new java.awt.Color(0, 0, 0));
        frame_bawah.setForeground(new java.awt.Color(255, 255, 255));
        frame_bawah.setToolTipText("");
        frame_bawah.setAutoscrolls(true);
        frame_bawah.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        frame_bawah.setFont(new java.awt.Font("Segoe UI", 0, 1)); // NOI18N
        frame_bawah.setOpaque(false);

        toRegister_text.setForeground(new java.awt.Color(255, 255, 255));
        toRegister_text.setText("Don’t have an Account?");

        toRegister_button.setFont(new java.awt.Font("Onest Bold", 0, 12)); // NOI18N
        toRegister_button.setForeground(new java.awt.Color(255, 255, 255));
        toRegister_button.setText("Register");
        toRegister_button.setBorder(null);
        toRegister_button.setContentAreaFilled(false);
        toRegister_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        toRegister_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toRegister_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frame_bawahLayout = new javax.swing.GroupLayout(frame_bawah);
        frame_bawah.setLayout(frame_bawahLayout);
        frame_bawahLayout.setHorizontalGroup(
            frame_bawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_bawahLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(frame_bawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_bawahLayout.createSequentialGroup()
                        .addComponent(toRegister_text, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_bawahLayout.createSequentialGroup()
                        .addComponent(toRegister_button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))))
        );
        frame_bawahLayout.setVerticalGroup(
            frame_bawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_bawahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toRegister_text, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toRegister_button, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(frame_bawah, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 140, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 3)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BG.png"))); // NOI18N
        jLabel3.setToolTipText("");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel3.setAutoscrolls(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        String username = username_field.getText();
        String password = new String(password_field.getPassword());
        UserFunctions userFunc = new UserFunctions();

        if (userFunc.loginUser(username, password)) {
            System.out.println("Login successful!");
            this.dispose();
            JOptionPane.showMessageDialog(null, "Login berhasil!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            System.out.println("Login failed!");
        }
    }//GEN-LAST:event_login_buttonActionPerformed

    private void password_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_fieldActionPerformed

    private void toRegister_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toRegister_buttonActionPerformed
        register goToRegister = new register();
        goToRegister.setVisible(true);
        goToRegister.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_toRegister_buttonActionPerformed

    private void username_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_fieldActionPerformed
        
    }//GEN-LAST:event_username_fieldActionPerformed

    private void username_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_fieldFocusGained
        if (username_field.getText().equals("  Enter Username")){
            username_field.setText("");
            username_field.setForeground(new Color(255, 255, 255));
            username_field.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        }
    }//GEN-LAST:event_username_fieldFocusGained

    private void username_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_fieldFocusLost
        if (username_field.getText().equals("")){
            username_field.setText("  Enter Username");
            username_field.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_username_fieldFocusLost

    private void password_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_fieldFocusGained
        if (String.valueOf(password_field.getPassword()).equals("  Enter Password")) {
            password_field.setText("");
            password_field.setFont(new Font("Segoe UI", Font.PLAIN, 13));
            password_field.setForeground(new Color(255, 255, 255));
            password_field.setEchoChar('*');
        }
    }//GEN-LAST:event_password_fieldFocusGained

    private void password_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_fieldFocusLost
        if (String.valueOf(password_field.getPassword()).isEmpty()) {
            password_field.setText("  Enter Password");
            password_field.setForeground(new Color(153, 153, 153));
            password_field.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_password_fieldFocusLost

    private void username_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_fieldKeyPressed
        if(evt.getKeyCode() == 0x0a){
            password_field.requestFocus();
        }
    }//GEN-LAST:event_username_fieldKeyPressed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                login login = new login();
                login.setVisible(true);
                login.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel frame_atas;
    private javax.swing.JPanel frame_bawah;
    private javax.swing.JPanel frame_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login_button;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JLabel password_text;
    private javax.swing.JButton toRegister_button;
    private javax.swing.JLabel toRegister_text;
    private javax.swing.JTextField username_field;
    private javax.swing.JLabel username_text;
    // End of variables declaration//GEN-END:variables
}
