/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import Data.Biodata;
import Data.Users;
import dbConnection.Connector;
import java.awt.Color;
import java.awt.Font;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class profile extends javax.swing.JFrame {

    private Users user;
    /**
     * Creates new form login
     */
    public profile() {
        initComponents();
        email_field.setBackground(new java.awt.Color(0,0,0,1));
        email_field.setText("  Masukkan email");
        email_field.setFont(new Font("Segoe UI", Font.ITALIC, 13));
        email_field.setForeground(new Color(153, 153, 153));
    }

    public void setUser(Users user){
        this.user = user;
        this.user = user;
        if (user instanceof Biodata) {
            Biodata biodata = (Biodata) user;    
            String email = biodata.getEmail();
            email_field.setText(email);
            email_field.setForeground(new Color(255, 255, 255));
            email_field.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        }
    }
    
    public Users getUser(){
        return this.user;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        frame_field = new javax.swing.JPanel();
        frame_bawah = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        email_field = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        ubahPass_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        profil_button = new javax.swing.JButton();
        back_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        update_button = new javax.swing.JButton();
        LogOut_button = new javax.swing.JButton();
        delete_button2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        frame_field.setBackground(new java.awt.Color(0, 0, 0));
        frame_field.setForeground(new java.awt.Color(255, 255, 255));
        frame_field.setAutoscrolls(true);
        frame_field.setOpaque(false);

        frame_bawah.setBackground(new java.awt.Color(0, 0, 0));
        frame_bawah.setToolTipText("");
        frame_bawah.setAutoscrolls(true);
        frame_bawah.setOpaque(false);

        jLabel7.setText(" ");

        javax.swing.GroupLayout frame_bawahLayout = new javax.swing.GroupLayout(frame_bawah);
        frame_bawah.setLayout(frame_bawahLayout);
        frame_bawahLayout.setHorizontalGroup(
            frame_bawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_bawahLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        frame_bawahLayout.setVerticalGroup(
            frame_bawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_bawahLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        email_field.setFont(new java.awt.Font("Onest Regular", 0, 14)); // NOI18N
        email_field.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), null));
        email_field.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        email_field.setMargin(new java.awt.Insets(1, 10, 1, 1));
        email_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                email_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                email_fieldFocusLost(evt);
            }
        });
        email_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_fieldActionPerformed(evt);
            }
        });

        emailLabel.setBackground(new java.awt.Color(255, 255, 255));
        emailLabel.setFont(new java.awt.Font("Onest Light", 0, 12)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setText("Email:");

        ubahPass_button.setFont(new java.awt.Font("Onest Bold", 0, 12)); // NOI18N
        ubahPass_button.setForeground(new java.awt.Color(255, 255, 255));
        ubahPass_button.setText("Ubah password?");
        ubahPass_button.setBorder(null);
        ubahPass_button.setContentAreaFilled(false);
        ubahPass_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ubahPass_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahPass_buttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Onest Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Edit Profile");

        profil_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.png"))); // NOI18N
        profil_button.setBorderPainted(false);
        profil_button.setContentAreaFilled(false);
        profil_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profil_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profil_buttonActionPerformed(evt);
            }
        });

        back_button.setBackground(new java.awt.Color(0, 0, 114));
        back_button.setFont(new java.awt.Font("Onest Light", 0, 12)); // NOI18N
        back_button.setForeground(new java.awt.Color(255, 255, 255));
        back_button.setText("Back");
        back_button.setBorder(null);
        back_button.setBorderPainted(false);
        back_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        delete_button.setBackground(new java.awt.Color(115, 0, 0));
        delete_button.setFont(new java.awt.Font("Onest Light", 0, 12)); // NOI18N
        delete_button.setForeground(new java.awt.Color(255, 255, 255));
        delete_button.setText("Delete");
        delete_button.setBorder(null);
        delete_button.setBorderPainted(false);
        delete_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        update_button.setBackground(new java.awt.Color(30, 50, 0));
        update_button.setFont(new java.awt.Font("Onest Light", 0, 12)); // NOI18N
        update_button.setForeground(new java.awt.Color(255, 255, 255));
        update_button.setText("Update");
        update_button.setBorder(null);
        update_button.setBorderPainted(false);
        update_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        LogOut_button.setBackground(new java.awt.Color(93, 0, 0));
        LogOut_button.setFont(new java.awt.Font("Onest Light", 0, 12)); // NOI18N
        LogOut_button.setForeground(new java.awt.Color(255, 255, 255));
        LogOut_button.setText("Log Out");
        LogOut_button.setBorder(null);
        LogOut_button.setBorderPainted(false);
        LogOut_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOut_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOut_buttonActionPerformed(evt);
            }
        });

        delete_button2.setBackground(new java.awt.Color(90, 0, 0));
        delete_button2.setFont(new java.awt.Font("Onest Light", 0, 12)); // NOI18N
        delete_button2.setForeground(new java.awt.Color(255, 255, 255));
        delete_button2.setText("Delete Account");
        delete_button2.setBorder(null);
        delete_button2.setBorderPainted(false);
        delete_button2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frame_fieldLayout = new javax.swing.GroupLayout(frame_field);
        frame_field.setLayout(frame_fieldLayout);
        frame_fieldLayout.setHorizontalGroup(
            frame_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_fieldLayout.createSequentialGroup()
                .addGroup(frame_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_fieldLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ubahPass_button, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(frame_fieldLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(frame_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(frame_fieldLayout.createSequentialGroup()
                                .addComponent(LogOut_button, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(delete_button2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(frame_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(frame_fieldLayout.createSequentialGroup()
                                    .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(frame_fieldLayout.createSequentialGroup()
                                    .addComponent(profil_button)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(frame_bawah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frame_fieldLayout.setVerticalGroup(
            frame_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_fieldLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(frame_bawah, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
            .addGroup(frame_fieldLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(frame_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(frame_fieldLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(profil_button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frame_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ubahPass_button, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addGroup(frame_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogOut_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_button2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(frame_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 320, 440));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BG.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        boolean check = false;
        String queryUpdate = "UPDATE biodata " +
                                    "JOIN users ON users.biodata_id = biodata.biodata_id " +
                                    "SET biodata.email = '" + email_field.getText() + "' " +
                                    "WHERE users.username = '" + user.getUsername() + "'";
        Biodata biodata = (Biodata) user;
        
        String emailRegex = "^[\\w.%+-]+@[\\w.-]+\\.[a-zA-Z]{2,}$";
        if (Pattern.matches(emailRegex, email_field.getText())){
            check = true;  
        }
            
        Connector conn = new Connector();
        if (conn.executeUpdate(queryUpdate) && check==true && !biodata.getEmail().equals(email_field.getText())){
            biodata.setEmail(email_field.getText());
            JOptionPane.showMessageDialog(null, "Email berhasil diganti!", "Success", JOptionPane.INFORMATION_MESSAGE);
            dashboard db = new dashboard();
            db.setUser(this.user);
            db.setVisible(true);
            db.setSize(330, 545);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Email tidak valid!", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_update_buttonActionPerformed

    private void email_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_fieldActionPerformed

    private void email_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_fieldFocusLost
        if (email_field.getText().equals("")){
            email_field.setText("  Masukkan email");
            email_field.setForeground(new Color(153, 153, 153));
            email_field.setFont(new Font("Segoe UI", Font.ITALIC, 13));
        }
    }//GEN-LAST:event_email_fieldFocusLost

    private void email_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_fieldFocusGained
        if (email_field.getText().equals("  Masukkan email")){
            email_field.setText("");
            email_field.setForeground(new Color(255, 255, 255));
            email_field.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        }
    }//GEN-LAST:event_email_fieldFocusGained

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        dashboard db = new dashboard();
        db.setUser(this.user);
        db.setVisible(true);
        db.setSize(330, 545);
        this.dispose();
    }//GEN-LAST:event_back_buttonActionPerformed

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        email_field.setText("  Masukkan email");
        email_field.setForeground(new Color(153, 153, 153));
        email_field.setFont(new Font("Segoe UI", Font.ITALIC, 13));
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void profil_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profil_buttonActionPerformed
        
    }//GEN-LAST:event_profil_buttonActionPerformed

    private void ubahPass_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahPass_buttonActionPerformed
       
    }//GEN-LAST:event_ubahPass_buttonActionPerformed

    private void LogOut_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOut_buttonActionPerformed
        login login = new login();
        login.setUsername(user.getUsername());
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_LogOut_buttonActionPerformed

    private void delete_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_button2ActionPerformed
        user.deleteUser();
        login login = new login();
        login.setUsername(user.getUsername());
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_delete_button2ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                profile login = new profile();
                login.setVisible(true);
                login.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOut_button;
    private javax.swing.JButton back_button;
    private javax.swing.JButton delete_button;
    private javax.swing.JButton delete_button2;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField email_field;
    private javax.swing.JPanel frame_bawah;
    private javax.swing.JPanel frame_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton profil_button;
    private javax.swing.JButton ubahPass_button;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables
}
