/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import dbConnection.*;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public register() {
        initComponents();
        frame_atas.setOpaque(false);
        frame_bawah.setOpaque(false);
        frame_field.setOpaque(false);
        username_field.setBackground(new java.awt.Color(0,0,0,1));
        username_field.setForeground(java.awt.Color.WHITE);
        email_field.setBackground(new java.awt.Color(0,0,0,1));
        email_field.setForeground(java.awt.Color.WHITE);
        password_field.setBackground(new java.awt.Color(0,0,0,1));
        password_field.setForeground(java.awt.Color.WHITE);
        username_field.setText("  Enter Username");
        username_field.setFont(new Font("Segoe UI", Font.ITALIC, 13));
        username_field.setForeground(new Color(153, 153, 153));
        email_field.setText("  Enter Email");
        email_field.setFont(new Font("Segoe UI", Font.ITALIC, 13));
        email_field.setForeground(new Color(153, 153, 153));
        password_field.setText("  Enter Password");
        password_field.setFont(new Font("Segoe UI", Font.ITALIC, 13));
        password_field.setForeground(new Color(153, 153, 153));
        password_field.setEchoChar((char) 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        frame_atas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        frame_field = new javax.swing.JPanel();
        email_field = new javax.swing.JTextField();
        register_button = new javax.swing.JButton();
        username_text = new javax.swing.JLabel();
        email_text = new javax.swing.JLabel();
        frame_bawah = new javax.swing.JPanel();
        toRegister_text = new javax.swing.JLabel();
        toRegister_button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        password_field = new javax.swing.JPasswordField();
        password_text = new javax.swing.JLabel();
        username_field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        frame_atas.setBackground(new java.awt.Color(0, 0, 0));
        frame_atas.setForeground(new java.awt.Color(255, 255, 255));
        frame_atas.setAutoscrolls(true);
        frame_atas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        frame_atas.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Onest Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome !");

        jLabel2.setFont(new java.awt.Font("Onest Light", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Please Create your Account");

        javax.swing.GroupLayout frame_atasLayout = new javax.swing.GroupLayout(frame_atas);
        frame_atas.setLayout(frame_atasLayout);
        frame_atasLayout.setHorizontalGroup(
            frame_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_atasLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(frame_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_atasLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_atasLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(91, 91, 91))))
        );
        frame_atasLayout.setVerticalGroup(
            frame_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_atasLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jPanel1.add(frame_atas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 160));

        frame_field.setBackground(new java.awt.Color(0, 0, 0));
        frame_field.setForeground(new java.awt.Color(255, 255, 255));
        frame_field.setAutoscrolls(true);
        frame_field.setOpaque(false);

        email_field.setFont(new java.awt.Font("Onest Regular", 0, 14)); // NOI18N
        email_field.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        email_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                email_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                email_fieldFocusLost(evt);
            }
        });
        email_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_fieldActionPerformed(evt);
            }
        });
        email_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                email_fieldKeyPressed(evt);
            }
        });

        register_button.setBackground(new java.awt.Color(30, 50, 0));
        register_button.setFont(new java.awt.Font("Onest Light", 0, 12)); // NOI18N
        register_button.setForeground(new java.awt.Color(255, 255, 255));
        register_button.setText("Register");
        register_button.setBorder(null);
        register_button.setBorderPainted(false);
        register_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_buttonActionPerformed(evt);
            }
        });

        username_text.setBackground(new java.awt.Color(255, 255, 255));
        username_text.setFont(new java.awt.Font("Onest Light", 0, 12)); // NOI18N
        username_text.setForeground(new java.awt.Color(255, 255, 255));
        username_text.setText("Username: ");

        email_text.setFont(new java.awt.Font("Onest Light", 0, 12)); // NOI18N
        email_text.setForeground(new java.awt.Color(255, 255, 255));
        email_text.setText("Email:");

        frame_bawah.setBackground(new java.awt.Color(0, 0, 0));
        frame_bawah.setToolTipText("");
        frame_bawah.setAutoscrolls(true);
        frame_bawah.setOpaque(false);

        toRegister_text.setForeground(new java.awt.Color(255, 255, 255));
        toRegister_text.setText("Already have an Account? ");

        toRegister_button.setFont(new java.awt.Font("Onest Bold", 0, 12)); // NOI18N
        toRegister_button.setForeground(new java.awt.Color(255, 255, 255));
        toRegister_button.setText("Login");
        toRegister_button.setBorder(null);
        toRegister_button.setContentAreaFilled(false);
        toRegister_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        toRegister_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toRegister_buttonActionPerformed(evt);
            }
        });

        jLabel7.setText(" ");

        javax.swing.GroupLayout frame_bawahLayout = new javax.swing.GroupLayout(frame_bawah);
        frame_bawah.setLayout(frame_bawahLayout);
        frame_bawahLayout.setHorizontalGroup(
            frame_bawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_bawahLayout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(frame_bawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(frame_bawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_bawahLayout.createSequentialGroup()
                            .addComponent(toRegister_text, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(58, 58, 58))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_bawahLayout.createSequentialGroup()
                            .addComponent(toRegister_button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(95, 95, 95)))))
        );
        frame_bawahLayout.setVerticalGroup(
            frame_bawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_bawahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toRegister_text, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toRegister_button, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        password_field.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        password_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                password_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                password_fieldFocusLost(evt);
            }
        });
        password_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_fieldActionPerformed(evt);
            }
        });

        password_text.setFont(new java.awt.Font("Onest Light", 0, 12)); // NOI18N
        password_text.setForeground(new java.awt.Color(255, 255, 255));
        password_text.setText("Password:");

        username_field.setFont(new java.awt.Font("Onest Regular", 0, 14)); // NOI18N
        username_field.setToolTipText("");
        username_field.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        username_field.setMargin(new java.awt.Insets(0, 0, 0, 0));
        username_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                username_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                username_fieldFocusLost(evt);
            }
        });
        username_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_fieldActionPerformed(evt);
            }
        });
        username_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                username_fieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout frame_fieldLayout = new javax.swing.GroupLayout(frame_field);
        frame_field.setLayout(frame_fieldLayout);
        frame_fieldLayout.setHorizontalGroup(
            frame_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_fieldLayout.createSequentialGroup()
                .addGroup(frame_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frame_fieldLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(frame_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(username_text, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email_text, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(register_button, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(email_field, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(password_text, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password_field)
                            .addComponent(username_field)))
                    .addGroup(frame_fieldLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(frame_bawah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        frame_fieldLayout.setVerticalGroup(
            frame_fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_fieldLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(username_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(email_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(password_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(register_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(frame_bawah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(frame_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 310, 380));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BG.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 550));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void email_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_fieldActionPerformed
        
    }//GEN-LAST:event_email_fieldActionPerformed

    private void register_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_buttonActionPerformed
        String username = username_field.getText();
        String password = new String(password_field.getPassword());
        String email = email_field.getText();
        UserFunctions userFunc = new UserFunctions();
        
        if (userFunc.registerUser(username, password, email)) {
            System.out.println("Login successful!");
            login login = new login();
            login.setVisible(true);
            login.setLocationRelativeTo(null);
            this.dispose();
            JOptionPane.showMessageDialog(null, "Registrasi berhasil!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            System.out.println("Login failed!");
        }
    }//GEN-LAST:event_register_buttonActionPerformed

    private void toRegister_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toRegister_buttonActionPerformed
        login goToLogin = new login();
        goToLogin.setVisible(true);
        goToLogin.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_toRegister_buttonActionPerformed

    private void password_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_fieldActionPerformed

    private void username_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_fieldActionPerformed

    private void username_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_fieldFocusGained
        if (username_field.getText().equals("  Enter Username")){
            username_field.setText("");
            username_field.setForeground(new Color(255, 255, 255));
            username_field.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        }
    }//GEN-LAST:event_username_fieldFocusGained

    private void username_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_fieldFocusLost
        if (username_field.getText().equals("")){
            username_field.setText("  Enter Username");
            username_field.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_username_fieldFocusLost

    private void email_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_fieldFocusGained
        if (email_field.getText().equals("  Enter Email")){
            email_field.setText("");
            email_field.setForeground(new Color(255, 255, 255));
            email_field.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        }
    }//GEN-LAST:event_email_fieldFocusGained

    private void email_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_fieldFocusLost
        if (email_field.getText().equals("")){
            email_field.setText("  Enter Email");
            email_field.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_email_fieldFocusLost

    private void password_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_fieldFocusGained
        if (String.valueOf(password_field.getPassword()).equals("  Enter Password")) {
            password_field.setText("");
            password_field.setFont(new Font("Segoe UI", Font.PLAIN, 13));
            password_field.setForeground(new Color(255, 255, 255));
            password_field.setEchoChar('*');
        }
    }//GEN-LAST:event_password_fieldFocusGained

    private void password_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_fieldFocusLost
        if (String.valueOf(password_field.getPassword()).isEmpty()) {
            password_field.setText("  Enter Password");
            password_field.setForeground(new Color(153, 153, 153));
            password_field.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_password_fieldFocusLost

    private void username_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_fieldKeyPressed
        if(evt.getKeyCode() == 0x0a){
            email_field.requestFocus();
        }
    }//GEN-LAST:event_username_fieldKeyPressed

    private void email_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_email_fieldKeyPressed
        if(evt.getKeyCode() == 0x0a){
            password_field.requestFocus();
        }
    }//GEN-LAST:event_email_fieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                register register = new register();
                register.setVisible(true);
                register.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email_field;
    private javax.swing.JLabel email_text;
    private javax.swing.JPanel frame_atas;
    private javax.swing.JPanel frame_bawah;
    private javax.swing.JPanel frame_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JLabel password_text;
    private javax.swing.JButton register_button;
    private javax.swing.JButton toRegister_button;
    private javax.swing.JLabel toRegister_text;
    private javax.swing.JTextField username_field;
    private javax.swing.JLabel username_text;
    // End of variables declaration//GEN-END:variables
}
