/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import Data.*;
/**
 *
 * @author ASUS
 */
public class riwayat extends javax.swing.JFrame {
    private Users user;

    /**
     * Creates new form login
     */
    public riwayat() {
        initComponents();
        tanggal.setBackground(new java.awt.Color(10,10,10,20));
        totalP_box.setBackground(new java.awt.Color(10,10,10,20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parent = new javax.swing.JPanel();
        totalPengeluaran_field = new javax.swing.JLabel();
        total_pengeluaran_text = new javax.swing.JLabel();
        right_button = new javax.swing.JButton();
        left_button = new javax.swing.JButton();
        tahun = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        totalP_box = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        parent.setMaximumSize(new java.awt.Dimension(320, 800));
        parent.setOpaque(false);
        parent.setPreferredSize(new java.awt.Dimension(320, 800));
        parent.setLayout(null);

        totalPengeluaran_field.setFont(new java.awt.Font("Onest Bold", 0, 12)); // NOI18N
        totalPengeluaran_field.setForeground(new java.awt.Color(255, 255, 255));
        totalPengeluaran_field.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        totalPengeluaran_field.setText("XXXXXXX");
        parent.add(totalPengeluaran_field);
        totalPengeluaran_field.setBounds(210, 160, 120, 30);

        total_pengeluaran_text.setFont(new java.awt.Font("Onest Bold", 0, 12)); // NOI18N
        total_pengeluaran_text.setForeground(new java.awt.Color(255, 255, 255));
        total_pengeluaran_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_pengeluaran_text.setText("Total pengeluaran:       Rp.");
        parent.add(total_pengeluaran_text);
        total_pengeluaran_text.setBounds(50, 150, 160, 50);

        right_button.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        right_button.setForeground(new java.awt.Color(255, 255, 255));
        right_button.setText("<");
        right_button.setContentAreaFilled(false);
        right_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        right_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                right_buttonActionPerformed(evt);
            }
        });
        parent.add(right_button);
        right_button.setBounds(30, 80, 50, 48);

        left_button.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        left_button.setForeground(new java.awt.Color(255, 255, 255));
        left_button.setText(">");
        left_button.setContentAreaFilled(false);
        left_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        left_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                left_buttonActionPerformed(evt);
            }
        });
        parent.add(left_button);
        left_button.setBounds(240, 80, 50, 48);

        tahun.setFont(new java.awt.Font("Onest Bold", 0, 16)); // NOI18N
        tahun.setForeground(new java.awt.Color(255, 255, 255));
        tahun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tahun.setText("Bulan_Tahun");
        parent.add(tahun);
        tahun.setBounds(70, 80, 180, 50);

        tanggal.setBackground(new java.awt.Color(51, 102, 0));
        tanggal.setForeground(new java.awt.Color(255, 255, 255));
        tanggal.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), null));
        tanggal.setOpaque(true);
        parent.add(tanggal);
        tanggal.setBounds(30, 80, 260, 50);

        totalP_box.setBackground(new java.awt.Color(51, 102, 0));
        totalP_box.setForeground(new java.awt.Color(255, 255, 255));
        totalP_box.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), null));
        totalP_box.setOpaque(true);
        parent.add(totalP_box);
        totalP_box.setBounds(30, 150, 260, 50);

        jLabel1.setFont(new java.awt.Font("Onest Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Riwayat Pengeluaran");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        parent.add(jLabel1);
        jLabel1.setBounds(60, 20, 200, 40);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setForeground(new java.awt.Color(255, 255, 255));
        bg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BG.png"))); // NOI18N
        bg.setAlignmentX(0.5F);
        bg.setName(""); // NOI18N
        bg.setRequestFocusEnabled(false);
        parent.add(bg);
        bg.setBounds(0, 0, 320, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parent, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        setBounds(560, 160, 332, 556);
    }// </editor-fold>//GEN-END:initComponents

    public void setUser(Users user){
        this.user = user;
    }
    
    public Users getUser(){
        return this.user;
    }
    
    private void right_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_right_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_right_buttonActionPerformed

    private void left_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_left_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_left_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(riwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(riwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(riwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(riwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                riwayat db = new riwayat();
                db.setVisible(true);
                db.setSize(330, 545);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton left_button;
    private javax.swing.JPanel parent;
    private javax.swing.JButton right_button;
    private javax.swing.JLabel tahun;
    private javax.swing.JLabel tanggal;
    private javax.swing.JLabel totalP_box;
    private javax.swing.JLabel totalPengeluaran_field;
    private javax.swing.JLabel total_pengeluaran_text;
    // End of variables declaration//GEN-END:variables
}
